// data source: https://sto.fandom.com/wiki/Bridge_officer_and_kit_abilities
let abilitydata = [
{ type: "Engineering", name: "Aceton Beam", level: "I", rank: 3 },
{ type: "Engineering", name: "Aceton Beam", level: "II", rank: 4 },
{ type: "Engineering", name: "Aceton Beam", level: "III", rank: 4 },
{ type: "Engineering", name: "Auxiliary to Battery", level: "I", rank: 2 },
{ type: "Engineering", name: "Auxiliary to Battery", level: "II", rank: 3 },
{ type: "Engineering", name: "Auxiliary to Battery", level: "III", rank: 4 },
{ type: "Engineering", name: "Auxiliary to Dampeners", level: "I", rank: 2 },
{ type: "Engineering", name: "Auxiliary to Dampeners", level: "II", rank: 3 },
{ type: "Engineering", name: "Auxiliary to Dampeners", level: "III", rank: 4 },
{ type: "Engineering", name: "Auxiliary to Structural", level: "I", rank: 2 },
{ type: "Engineering", name: "Auxiliary to Structural", level: "II", rank: 3 },
{ type: "Engineering", name: "Auxiliary to Structural", level: "III", rank: 4 },
{ type: "Engineering", name: "Boarding Party", level: "I", rank: 2 },
{ type: "Engineering", name: "Boarding Party", level: "II", rank: 3 },
{ type: "Engineering", name: "Boarding Party", level: "III", rank: 4 },
{ type: "Engineering", name: "Deploy Construction Shuttle Wing", level: "I", rank: 1 },
{ type: "Engineering", name: "Deploy Construction Shuttle Wing", level: "II", rank: 2 },
{ type: "Engineering", name: "Deploy Construction Shuttle Wing", level: "III", rank: 3 },
{ type: "Engineering", name: "Directed Energy Modulation", level: "I", rank: 2 },
{ type: "Engineering", name: "Directed Energy Modulation", level: "II", rank: 3 },
{ type: "Engineering", name: "Directed Energy Modulation", level: "III", rank: 4 },
{ type: "Engineering", name: "Eject Warp Plasma", level: "I", rank: 3 },
{ type: "Engineering", name: "Eject Warp Plasma", level: "II", rank: 4 },
{ type: "Engineering", name: "Eject Warp Plasma", level: "III", rank: 4 },
{ type: "Engineering", name: "Emergency Power to Auxiliary", level: "I", rank: 1 },
{ type: "Engineering", name: "Emergency Power to Auxiliary", level: "II", rank: 2 },
{ type: "Engineering", name: "Emergency Power to Auxiliary", level: "III", rank: 3 },
{ type: "Engineering", name: "Emergency Power to Engines", level: "I", rank: 1 },
{ type: "Engineering", name: "Emergency Power to Engines", level: "II", rank: 2 },
{ type: "Engineering", name: "Emergency Power to Engines", level: "III", rank: 3 },
{ type: "Engineering", name: "Emergency Power to Shields", level: "I", rank: 1 },
{ type: "Engineering", name: "Emergency Power to Shields", level: "II", rank: 2 },
{ type: "Engineering", name: "Emergency Power to Shields", level: "III", rank: 3 },
{ type: "Engineering", name: "Emergency Power to Weapons", level: "I", rank: 1 },
{ type: "Engineering", name: "Emergency Power to Weapons", level: "II", rank: 2 },
{ type: "Engineering", name: "Emergency Power to Weapons", level: "III", rank: 3 },
{ type: "Engineering", name: "Emit Unstable Warp Bubble", level: "I", rank: 2 },
{ type: "Engineering", name: "Emit Unstable Warp Bubble", level: "II", rank: 3 },
{ type: "Engineering", name: "Emit Unstable Warp Bubble", level: "III", rank: 4 },
{ type: "Engineering", name: "Endothermic Inhibitor Beam", level: "I", rank: 1 },
{ type: "Engineering", name: "Endothermic Inhibitor Beam", level: "II", rank: 2 },
{ type: "Engineering", name: "Endothermic Inhibitor Beam", level: "III", rank: 3 },
{ type: "Engineering", name: "Engineering Team", level: "I", rank: 1 },
{ type: "Engineering", name: "Engineering Team", level: "II", rank: 2 },
{ type: "Engineering", name: "Engineering Team", level: "III", rank: 3 },
{ type: "Engineering", name: "Extend Shields", level: "I", rank: 2 },
{ type: "Engineering", name: "Extend Shields", level: "II", rank: 3 },
{ type: "Engineering", name: "Extend Shields", level: "III", rank: 4 },
{ type: "Engineering", name: "Let It Go", level: "I", rank: 1 },
{ type: "Engineering", name: "Let It Go", level: "II", rank: 2 },
{ type: "Engineering", name: "Let It Go", level: "III", rank: 3 },
{ type: "Engineering", name: "Overload Integrity Field", level: "I", rank: 1 },
{ type: "Engineering", name: "Overload Integrity Field", level: "II", rank: 2 },
{ type: "Engineering", name: "Overload Integrity Field", level: "III", rank: 3 },
{ type: "Engineering", name: "Reverse Shield Polarity", level: "I", rank: 2 },
{ type: "Engineering", name: "Reverse Shield Polarity", level: "II", rank: 3 },
{ type: "Engineering", name: "Reverse Shield Polarity", level: "III", rank: 4 },
{ type: "Engineering", name: "Structural Integrity Collapse", level: "I", rank: 1 },
{ type: "Engineering", name: "Structural Integrity Collapse", level: "II", rank: 2 },
{ type: "Engineering", name: "Structural Integrity Collapse", level: "III", rank: 3 },
{ type: "Science", name: "Charged Particle Burst", level: "I", rank: 2 },
{ type: "Science", name: "Charged Particle Burst", level: "II", rank: 3 },
{ type: "Science", name: "Charged Particle Burst", level: "III", rank: 4 },
{ type: "Science", name: "Delayed Overload Cascade", level: "I", rank: 1 },
{ type: "Science", name: "Delayed Overload Cascade", level: "II", rank: 2 },
{ type: "Science", name: "Delayed Overload Cascade", level: "III", rank: 3 },
{ type: "Science", name: "Destabilizing Resonance Beam", level: "I", rank: 2 },
{ type: "Science", name: "Destabilizing Resonance Beam", level: "II", rank: 3 },
{ type: "Science", name: "Destabilizing Resonance Beam", level: "III", rank: 4 },
{ type: "Science", name: "Energy Siphon", level: "I", rank: 2 },
{ type: "Science", name: "Energy Siphon", level: "II", rank: 3 },
{ type: "Science", name: "Energy Siphon", level: "III", rank: 4 },
{ type: "Science", name: "Feedback Pulse", level: "I", rank: 2 },
{ type: "Science", name: "Feedback Pulse", level: "II", rank: 3 },
{ type: "Science", name: "Feedback Pulse", level: "III", rank: 4 },
{ type: "Science", name: "Gravity Well", level: "I", rank: 3 },
{ type: "Science", name: "Gravity Well", level: "II", rank: 4 },
{ type: "Science", name: "Gravity Well", level: "III", rank: 4 },
{ type: "Science", name: "Hazard Emitters", level: "I", rank: 1 },
{ type: "Science", name: "Hazard Emitters", level: "II", rank: 2 },
{ type: "Science", name: "Hazard Emitters", level: "III", rank: 3 },
{ type: "Science", name: "Jam Sensors", level: "I", rank: 1 },
{ type: "Science", name: "Jam Sensors", level: "II", rank: 2 },
{ type: "Science", name: "Jam Sensors", level: "III", rank: 3 },
{ type: "Science", name: "Mask Energy Signature", level: "I", rank: 1 },
{ type: "Science", name: "Mask Energy Signature", level: "II", rank: 2 },
{ type: "Science", name: "Mask Energy Signature", level: "III", rank: 3 },
{ type: "Science", name: "Photonic Officer", level: "I", rank: 2 },
{ type: "Science", name: "Photonic Officer", level: "II", rank: 3 },
{ type: "Science", name: "Photonic Officer", level: "III", rank: 4 },
{ type: "Science", name: "Photonic Shockwave", level: "I", rank: 3 },
{ type: "Science", name: "Photonic Shockwave", level: "II", rank: 4 },
{ type: "Science", name: "Photonic Shockwave", level: "III", rank: 4 },
{ type: "Science", name: "Polarize Hull", level: "I", rank: 1 },
{ type: "Science", name: "Polarize Hull", level: "II", rank: 2 },
{ type: "Science", name: "Polarize Hull", level: "III", rank: 3 },
{ type: "Science", name: "Science Team", level: "I", rank: 1 },
{ type: "Science", name: "Science Team", level: "II", rank: 2 },
{ type: "Science", name: "Science Team", level: "III", rank: 3 },
{ type: "Science", name: "Scramble Sensors", level: "I", rank: 2 },
{ type: "Science", name: "Scramble Sensors", level: "II", rank: 3 },
{ type: "Science", name: "Scramble Sensors", level: "III", rank: 4 },
{ type: "Science", name: "Structural Analysis", level: "I", rank: 1 },
{ type: "Science", name: "Structural Analysis", level: "II", rank: 2 },
{ type: "Science", name: "Structural Analysis", level: "III", rank: 3 },
{ type: "Science", name: "Subspace Vortex", level: "I", rank: 1 },
{ type: "Science", name: "Subspace Vortex", level: "II", rank: 2 },
{ type: "Science", name: "Subspace Vortex", level: "III", rank: 3 },
{ type: "Science", name: "Tachyon Beam", level: "I", rank: 1 },
{ type: "Science", name: "Tachyon Beam", level: "II", rank: 2 },
{ type: "Science", name: "Tachyon Beam", level: "III", rank: 3 },
{ type: "Science", name: "Tractor Beam Repulsors", level: "I", rank: 2 },
{ type: "Science", name: "Tractor Beam Repulsors", level: "II", rank: 3 },
{ type: "Science", name: "Tractor Beam Repulsors", level: "III", rank: 4 },
{ type: "Science", name: "Tractor Beam", level: "I", rank: 1 },
{ type: "Science", name: "Tractor Beam", level: "II", rank: 2 },
{ type: "Science", name: "Tractor Beam", level: "III", rank: 3 },
{ type: "Science", name: "Transfer Shield Strength", level: "I", rank: 1 },
{ type: "Science", name: "Transfer Shield Strength", level: "II", rank: 2 },
{ type: "Science", name: "Transfer Shield Strength", level: "III", rank: 3 },
{ type: "Science", name: "Tyken's Rift", level: "I", rank: 2 },
{ type: "Science", name: "Tyken's Rift", level: "II", rank: 3 },
{ type: "Science", name: "Tyken's Rift", level: "III", rank: 4 },
{ type: "Science", name: "Very Cold In Space", level: "I", rank: 1 },
{ type: "Science", name: "Very Cold In Space", level: "II", rank: 2 },
{ type: "Science", name: "Very Cold In Space", level: "III", rank: 3 },
{ type: "Science", name: "Viral Matrix", level: "I", rank: 3 },
{ type: "Science", name: "Viral Matrix", level: "II", rank: 4 },
{ type: "Science", name: "Viral Matrix", level: "III", rank: 4 },
{ type: "Tactical", name: "Attack Pattern Beta", level: "I", rank: 2 },
{ type: "Tactical", name: "Attack Pattern Beta", level: "II", rank: 3 },
{ type: "Tactical", name: "Attack Pattern Beta", level: "III", rank: 4 },
{ type: "Tactical", name: "Attack Pattern Delta", level: "I", rank: 2 },
{ type: "Tactical", name: "Attack Pattern Delta", level: "II", rank: 3 },
{ type: "Tactical", name: "Attack Pattern Delta", level: "III", rank: 4 },
{ type: "Tactical", name: "Attack Pattern Omega", level: "I", rank: 3 },
{ type: "Tactical", name: "Attack Pattern Omega", level: "II", rank: 4 },
{ type: "Tactical", name: "Attack Pattern Omega", level: "III", rank: 4 },
{ type: "Tactical", name: "Augment Boarding Party", level: "II", rank: 2 },
{ type: "Tactical", name: "Augment Boarding Party", level: "III", rank: 3 },
{ type: "Tactical", name: "Beams: Fire at Will", level: "I", rank: 1 },
{ type: "Tactical", name: "Beams: Fire at Will", level: "II", rank: 2 },
{ type: "Tactical", name: "Beams: Fire at Will", level: "III", rank: 3 },
{ type: "Tactical", name: "Beams: Overload", level: "I", rank: 1 },
{ type: "Tactical", name: "Beams: Overload", level: "II", rank: 2 },
{ type: "Tactical", name: "Beams: Overload", level: "III", rank: 3 },
{ type: "Tactical", name: "Best Served Cold", level: "I", rank: 1 },
{ type: "Tactical", name: "Best Served Cold", level: "II", rank: 2 },
{ type: "Tactical", name: "Best Served Cold", level: "III", rank: 3 },
{ type: "Tactical", name: "Cannon: Rapid Fire", level: "I", rank: 2 },
{ type: "Tactical", name: "Cannon: Rapid Fire", level: "II", rank: 3 },
{ type: "Tactical", name: "Cannon: Rapid Fire", level: "III", rank: 4 },
{ type: "Tactical", name: "Cannon: Scatter Volley", level: "I", rank: 2 },
{ type: "Tactical", name: "Cannon: Scatter Volley", level: "II", rank: 3 },
{ type: "Tactical", name: "Cannon: Scatter Volley", level: "III", rank: 4 },
{ type: "Tactical", name: "Dispersal Pattern Alpha", level: "I", rank: 2 },
{ type: "Tactical", name: "Dispersal Pattern Alpha", level: "II", rank: 3 },
{ type: "Tactical", name: "Dispersal Pattern Alpha", level: "III", rank: 4 },
{ type: "Tactical", name: "Dispersal Pattern Beta", level: "I", rank: 2 },
{ type: "Tactical", name: "Dispersal Pattern Beta", level: "II", rank: 3 },
{ type: "Tactical", name: "Dispersal Pattern Beta", level: "III", rank: 4 },
{ type: "Tactical", name: "Distributed Targeting", level: "I", rank: 1 },
{ type: "Tactical", name: "Distributed Targeting", level: "II", rank: 2 },
{ type: "Tactical", name: "Distributed Targeting", level: "III", rank: 3 },
{ type: "Tactical", name: "Focused Assault", level: "I", rank: 2 },
{ type: "Tactical", name: "Focused Assault", level: "II", rank: 3 },
{ type: "Tactical", name: "Focused Assault", level: "III", rank: 4 },
{ type: "Tactical", name: "Kemocite-Laced Weaponry", level: "I", rank: 1 },
{ type: "Tactical", name: "Kemocite-Laced Weaponry", level: "II", rank: 2 },
{ type: "Tactical", name: "Kemocite-Laced Weaponry", level: "III", rank: 3 },
{ type: "Tactical", name: "Tactical Team", level: "I", rank: 1 },
{ type: "Tactical", name: "Tactical Team", level: "II", rank: 2 },
{ type: "Tactical", name: "Tactical Team", level: "III", rank: 3 },
{ type: "Tactical", name: "Target Auxiliary Subsystems", level: "I", rank: 1 },
{ type: "Tactical", name: "Target Auxiliary Subsystems", level: "II", rank: 2 },
{ type: "Tactical", name: "Target Auxiliary Subsystems", level: "III", rank: 3 },
{ type: "Tactical", name: "Target Engines Subsystems", level: "I", rank: 1 },
{ type: "Tactical", name: "Target Engines Subsystems", level: "II", rank: 2 },
{ type: "Tactical", name: "Target Engines Subsystems", level: "III", rank: 3 },
{ type: "Tactical", name: "Target Shields Subsystems", level: "I", rank: 1 },
{ type: "Tactical", name: "Target Shields Subsystems", level: "II", rank: 2 },
{ type: "Tactical", name: "Target Shields Subsystems", level: "III", rank: 3 },
{ type: "Tactical", name: "Target Weapons Subsystems", level: "I", rank: 1 },
{ type: "Tactical", name: "Target Weapons Subsystems", level: "II", rank: 2 },
{ type: "Tactical", name: "Target Weapons Subsystems", level: "III", rank: 3 },
{ type: "Tactical", name: "Torpedo: High Yield", level: "I", rank: 1 },
{ type: "Tactical", name: "Torpedo: High Yield", level: "II", rank: 2 },
{ type: "Tactical", name: "Torpedo: High Yield", level: "III", rank: 3 },
{ type: "Tactical", name: "Torpedo: Spread", level: "I", rank: 1 },
{ type: "Tactical", name: "Torpedo: Spread", level: "II", rank: 2 },
{ type: "Tactical", name: "Torpedo: Spread", level: "III", rank: 3 },
{ type: "Command", name: "Ambush Point Marker", level: "I", rank: 2 },
{ type: "Command", name: "Ambush Point Marker", level: "II", rank: 3 },
{ type: "Command", name: "Ambush Point Marker", level: "III", rank: 4 },
{ type: "Command", name: "Call Emergency Artillery", level: "I", rank: 3 },
{ type: "Command", name: "Call Emergency Artillery", level: "II", rank: 4 },
{ type: "Command", name: "Call Emergency Artillery", level: "III", rank: 4 },
{ type: "Command", name: "Concentrate Firepower", level: "I", rank: 1 },
{ type: "Command", name: "Concentrate Firepower", level: "II", rank: 2 },
{ type: "Command", name: "Concentrate Firepower", level: "III", rank: 3 },
{ type: "Command", name: "Needs of the Many", level: "I", rank: 2 },
{ type: "Command", name: "Needs of the Many", level: "II", rank: 3 },
{ type: "Command", name: "Needs of the Many", level: "III", rank: 4 },
{ type: "Command", name: "Overwhelm Emitters", level: "I", rank: 1 },
{ type: "Command", name: "Overwhelm Emitters", level: "II", rank: 2 },
{ type: "Command", name: "Overwhelm Emitters", level: "III", rank: 3 },
{ type: "Command", name: "Phalanx Formation", level: "I", rank: 3 },
{ type: "Command", name: "Phalanx Formation", level: "II", rank: 4 },
{ type: "Command", name: "Phalanx Formation", level: "III", rank: 4 },
{ type: "Command", name: "Rally Point Marker", level: "I", rank: 2 },
{ type: "Command", name: "Rally Point Marker", level: "II", rank: 3 },
{ type: "Command", name: "Rally Point Marker", level: "III", rank: 4 },
{ type: "Command", name: "Reroute Power from Life Support", level: "I", rank: 1 },
{ type: "Command", name: "Reroute Power from Life Support", level: "II", rank: 2 },
{ type: "Command", name: "Reroute Power from Life Support", level: "III", rank: 3 },
{ type: "Command", name: "Subspace Interception", level: "I", rank: 2 },
{ type: "Command", name: "Subspace Interception", level: "II", rank: 3 },
{ type: "Command", name: "Subspace Interception", level: "III", rank: 4 },
{ type: "Command", name: "Suppression Barrage", level: "I", rank: 3 },
{ type: "Command", name: "Suppression Barrage", level: "II", rank: 4 },
{ type: "Command", name: "Suppression Barrage", level: "III", rank: 4 },
{ type: "Intelligence", name: "Electromagnetic Pulse Probe", level: "I", rank: 2 },
{ type: "Intelligence", name: "Electromagnetic Pulse Probe", level: "II", rank: 3 },
{ type: "Intelligence", name: "Electromagnetic Pulse Probe", level: "III", rank: 4 },
{ type: "Intelligence", name: "Energy Weapons: Surgical Strikes", level: "I", rank: 3 },
{ type: "Intelligence", name: "Energy Weapons: Surgical Strikes", level: "II", rank: 4 },
{ type: "Intelligence", name: "Energy Weapons: Surgical Strikes", level: "III", rank: 4 },
{ type: "Intelligence", name: "Evade Target Lock", level: "I", rank: 1 },
{ type: "Intelligence", name: "Evade Target Lock", level: "II", rank: 2 },
{ type: "Intelligence", name: "Evade Target Lock", level: "III", rank: 3 },
{ type: "Intelligence", name: "Intelligence Team", level: "I", rank: 1 },
{ type: "Intelligence", name: "Intelligence Team", level: "II", rank: 2 },
{ type: "Intelligence", name: "Intelligence Team", level: "III", rank: 3 },
{ type: "Intelligence", name: "Ionic Turbulence", level: "I", rank: 2 },
{ type: "Intelligence", name: "Ionic Turbulence", level: "II", rank: 3 },
{ type: "Intelligence", name: "Ionic Turbulence", level: "III", rank: 4 },
{ type: "Intelligence", name: "Kinetic Magnet", level: "I", rank: 2 },
{ type: "Intelligence", name: "Kinetic Magnet", level: "II", rank: 3 },
{ type: "Intelligence", name: "Kinetic Magnet", level: "III", rank: 4 },
{ type: "Intelligence", name: "Override Subsystem Safeties", level: "I", rank: 1 },
{ type: "Intelligence", name: "Override Subsystem Safeties", level: "II", rank: 2 },
{ type: "Intelligence", name: "Override Subsystem Safeties", level: "III", rank: 3 },
{ type: "Intelligence", name: "Subnucleonic Carrier Wave", level: "I", rank: 3 },
{ type: "Intelligence", name: "Subnucleonic Carrier Wave", level: "II", rank: 4 },
{ type: "Intelligence", name: "Subnucleonic Carrier Wave", level: "III", rank: 4 },
{ type: "Intelligence", name: "Subspace Beacon", level: "I", rank: 1 },
{ type: "Intelligence", name: "Subspace Beacon", level: "II", rank: 2 },
{ type: "Intelligence", name: "Subspace Beacon", level: "III", rank: 3 },
{ type: "Intelligence", name: "Torpedo: Transport Warhead", level: "I", rank: 3 },
{ type: "Intelligence", name: "Torpedo: Transport Warhead", level: "II", rank: 4 },
{ type: "Intelligence", name: "Torpedo: Transport Warhead", level: "III", rank: 4 },
{ type: "Intelligence", name: "Viral Impulse Burst", level: "I", rank: 1 },
{ type: "Intelligence", name: "Viral Impulse Burst", level: "II", rank: 2 },
{ type: "Intelligence", name: "Viral Impulse Burst", level: "III", rank: 3 },
{ type: "Miracle Worker", name: "Align Shield Frequencies", level: "I", rank: 1 },
{ type: "Miracle Worker", name: "Align Shield Frequencies", level: "II", rank: 2 },
{ type: "Miracle Worker", name: "Align Shield Frequencies", level: "III", rank: 3 },
{ type: "Miracle Worker", name: "Deploy Gravitic Induction Platform", level: "I", rank: 3 },
{ type: "Miracle Worker", name: "Deploy Gravitic Induction Platform", level: "II", rank: 4 },
{ type: "Miracle Worker", name: "Deploy Gravitic Induction Platform", level: "III", rank: 4 },
{ type: "Miracle Worker", name: "Destabilize Warp Core", level: "I", rank: 1 },
{ type: "Miracle Worker", name: "Destabilize Warp Core", level: "II", rank: 2 },
{ type: "Miracle Worker", name: "Destabilize Warp Core", level: "III", rank: 3 },
{ type: "Miracle Worker", name: "Energy Weapons: Exceed Rated Limits", level: "I", rank: 3 },
{ type: "Miracle Worker", name: "Energy Weapons: Exceed Rated Limits", level: "II", rank: 4 },
{ type: "Miracle Worker", name: "Energy Weapons: Exceed Rated Limits", level: "III", rank: 4 },
{ type: "Miracle Worker", name: "Mixed Armaments Synergy", level: "I", rank: 2 },
{ type: "Miracle Worker", name: "Mixed Armaments Synergy", level: "II", rank: 3 },
{ type: "Miracle Worker", name: "Mixed Armaments Synergy", level: "III", rank: 4 },
{ type: "Miracle Worker", name: "Narrow Sensor Bands", level: "I", rank: 1 },
{ type: "Miracle Worker", name: "Narrow Sensor Bands", level: "II", rank: 2 },
{ type: "Miracle Worker", name: "Narrow Sensor Bands", level: "III", rank: 3 },
{ type: "Miracle Worker", name: "Null Pointer Flood", level: "I", rank: 1 },
{ type: "Miracle Worker", name: "Null Pointer Flood", level: "II", rank: 2 },
{ type: "Miracle Worker", name: "Null Pointer Flood", level: "III", rank: 3 },
{ type: "Miracle Worker", name: "Overwhelm Power Regulators", level: "I", rank: 2 },
{ type: "Miracle Worker", name: "Overwhelm Power Regulators", level: "II", rank: 3 },
{ type: "Miracle Worker", name: "Overwhelm Power Regulators", level: "III", rank: 4 },
{ type: "Miracle Worker", name: "Reroute Shields to Hull Containment", level: "I", rank: 2 },
{ type: "Miracle Worker", name: "Reroute Shields to Hull Containment", level: "II", rank: 3 },
{ type: "Miracle Worker", name: "Reroute Shields to Hull Containment", level: "III", rank: 4 },
{ type: "Miracle Worker", name: "Torpedoes: Nanite Repair Payload", level: "I", rank: 1 },
{ type: "Miracle Worker", name: "Torpedoes: Nanite Repair Payload", level: "II", rank: 2 },
{ type: "Miracle Worker", name: "Torpedoes: Nanite Repair Payload", level: "III", rank: 3 },
{ type: "Pilot", name: "Attack Pattern Lambda", level: "I", rank: 1 },
{ type: "Pilot", name: "Attack Pattern Lambda", level: "II", rank: 2 },
{ type: "Pilot", name: "Attack Pattern Lambda", level: "III", rank: 3 },
{ type: "Pilot", name: "Clean Getaway", level: "I", rank: 2 },
{ type: "Pilot", name: "Clean Getaway", level: "II", rank: 3 },
{ type: "Pilot", name: "Clean Getaway", level: "III", rank: 4 },
{ type: "Pilot", name: "Coolant Ignition", level: "I", rank: 3 },
{ type: "Pilot", name: "Coolant Ignition", level: "II", rank: 4 },
{ type: "Pilot", name: "Coolant Ignition", level: "III", rank: 4 },
{ type: "Pilot", name: "Deploy Countermeasures", level: "I", rank: 1 },
{ type: "Pilot", name: "Deploy Countermeasures", level: "II", rank: 2 },
{ type: "Pilot", name: "Deploy Countermeasures", level: "III", rank: 3 },
{ type: "Pilot", name: "Fly Her Apart", level: "I", rank: 2 },
{ type: "Pilot", name: "Fly Her Apart", level: "II", rank: 3 },
{ type: "Pilot", name: "Fly Her Apart", level: "III", rank: 4 },
{ type: "Pilot", name: "Form Up", level: "I", rank: 3 },
{ type: "Pilot", name: "Form Up", level: "II", rank: 4 },
{ type: "Pilot", name: "Form Up", level: "III", rank: 4 },
{ type: "Pilot", name: "Hold Together", level: "I", rank: 2 },
{ type: "Pilot", name: "Hold Together", level: "II", rank: 3 },
{ type: "Pilot", name: "Hold Together", level: "III", rank: 4 },
{ type: "Pilot", name: "Lock Trajectory", level: "I", rank: 1 },
{ type: "Pilot", name: "Lock Trajectory", level: "II", rank: 2 },
{ type: "Pilot", name: "Lock Trajectory", level: "III", rank: 3 },
{ type: "Pilot", name: "Pilot Team", level: "I", rank: 1 },
{ type: "Pilot", name: "Pilot Team", level: "II", rank: 2 },
{ type: "Pilot", name: "Pilot Team", level: "III", rank: 3 },
{ type: "Pilot", name: "Reinforcements Squadron", level: "I", rank: 2 },
{ type: "Pilot", name: "Reinforcements Squadron", level: "II", rank: 3 },
{ type: "Pilot", name: "Reinforcements Squadron", level: "III", rank: 4 },
{ type: "Pilot", name: "Reroute Reserves to Weapons", level: "I", rank: 3 },
{ type: "Pilot", name: "Reroute Reserves to Weapons", level: "II", rank: 4 },
{ type: "Pilot", name: "Reroute Reserves to Weapons", level: "III", rank: 4 },
{ type: "Pilot", name: "Subspace Boom", level: "I", rank: 3 },
{ type: "Pilot", name: "Subspace Boom", level: "II", rank: 4 },
{ type: "Pilot", name: "Subspace Boom", level: "III", rank: 4 },
{ type: "Temporal", name: "Causal Reversion", level: "I", rank: 1 },
{ type: "Temporal", name: "Causal Reversion", level: "II", rank: 2 },
{ type: "Temporal", name: "Causal Reversion", level: "III", rank: 3 },
{ type: "Temporal", name: "Channeled Deconstruction", level: "I", rank: 1 },
{ type: "Temporal", name: "Channeled Deconstruction", level: "II", rank: 2 },
{ type: "Temporal", name: "Channeled Deconstruction", level: "III", rank: 3 },
{ type: "Temporal", name: "Chronometric Inversion Field", level: "I", rank: 2 },
{ type: "Temporal", name: "Chronometric Inversion Field", level: "II", rank: 3 },
{ type: "Temporal", name: "Chronometric Inversion Field", level: "III", rank: 4 },
{ type: "Temporal", name: "Entropic Cascade", level: "I", rank: 2 },
{ type: "Temporal", name: "Entropic Cascade", level: "II", rank: 3 },
{ type: "Temporal", name: "Entropic Cascade", level: "III", rank: 4 },
{ type: "Temporal", name: "Entropic Redistribution", level: "I", rank: 1 },
{ type: "Temporal", name: "Entropic Redistribution", level: "II", rank: 2 },
{ type: "Temporal", name: "Entropic Redistribution", level: "III", rank: 3 },
{ type: "Temporal", name: "Gravimetric Conversion", level: "I", rank: 2 },
{ type: "Temporal", name: "Gravimetric Conversion", level: "II", rank: 3 },
{ type: "Temporal", name: "Gravimetric Conversion", level: "III", rank: 4 },
{ type: "Temporal", name: "Heisenberg Amplifier", level: "I", rank: 1 },
{ type: "Temporal", name: "Heisenberg Amplifier", level: "II", rank: 2 },
{ type: "Temporal", name: "Heisenberg Amplifier", level: "III", rank: 3 },
{ type: "Temporal", name: "Rapid Decay", level: "I", rank: 2 },
{ type: "Temporal", name: "Rapid Decay", level: "II", rank: 3 },
{ type: "Temporal", name: "Rapid Decay", level: "III", rank: 4 },
{ type: "Temporal", name: "Recursive Shearing", level: "I", rank: 3 },
{ type: "Temporal", name: "Recursive Shearing", level: "II", rank: 4 },
{ type: "Temporal", name: "Recursive Shearing", level: "III", rank: 4 },
{ type: "Temporal", name: "Shared Fate", level: "I", rank: 2 },
{ type: "Temporal", name: "Shared Fate", level: "II", rank: 3 },
{ type: "Temporal", name: "Shared Fate", level: "III", rank: 4 },
{ type: "Temporal", name: "Timeline Collapse", level: "I", rank: 3 },
{ type: "Temporal", name: "Timeline Collapse", level: "II", rank: 4 },
{ type: "Temporal", name: "Timeline Collapse", level: "III", rank: 4 },
];