let attributedata = [
{ text: "Source", key: "source"},
{ text: "Bundle", key: "bundle"},
{ text: "Starter", key: "starter"},
{ text: "Faction", key: "faction"},
{ text: "Family", key: "family"},
{ text: "Mastery Package", key: "masterypackage"},
{ text: "Hull", key: "hull"},
{ text: "Hull Modifier", key: "hmod"},
{ text: "Shield Modifier", key: "smod"},
{ text: "Turn Rate", key: "turn"},
{ text: "Impulse Modifier", key: "imp"},
{ text: "Inertia Rating", key: "inrt"},
{ text: "Bonus Weapons Power", key: "wpower"},
{ text: "Bonus Shield Power", key: "spower"},
{ text: "Bonus Engine Power", key: "epower"},
{ text: "Bonus Auxilliary Power", key: "apower"},
{ text: "Fore + Aft Weapons", key: "fa"},
{ text: "Fore Weapons", key: "fore"},
{ text: "Aft Weapons", key: "aft"},
{ text: "Can Equip Dual Cannons", key: "dhc"},
{ text: "Experimental Weapon Slot", key: "exp"},
{ text: "Hangar Bays", key: "hangars"},
{ text: "Devices", key: "dev"},
{ text: "Fleet Grade", key: "fleet"},
{ text: "Tactical Consoles", key: "taccons"},
{ text: "Engineering Consoles", key: "engcons"},
{ text: "Science Consoles", key: "scicons"},
{ text: "Universal Consoles", key: "unicons"},
{ text: "CC: Weapon System Efficiency", key: "weapon"},
{ text: "CC: Shield Freq. Modulation", key: "shield"},
{ text: "CC: Strategic Maneuvering", key: "engine"},
{ text: "CC: Attract Fire", key: "threat"},
{ text: "Secondary Deflector", key: "secdef"},
{ text: "Subsytem Targeting", key: "subtargeting"},
{ text: "Sensor Analysis", key: "sensoranalysis"},
{ text: "Singularity", key: "singularity"},
{ text: "Cloak", key: "cloak"},
{ text: "Flanking", key: "flanking" }
];
