let attributedata = [
{ text: "Source", value: "source" },
{ text: "Bundle", value: "bundle" },
{ text: "Starter", value: "starter" },
{ text: "Faction", value: "faction" },
{ text: "Family", value: "family" },
{ text: "Mastery Package", value: "masterypackage" },
{ text: "Hull", value: "hull" },
{ text: "Hull Modifier", value: "hmod" },
{ text: "Shield Modifier", value: "smod" },
{ text: "Turn Rate", value: "turn" },
{ text: "Impulse Modifier", value: "imp" },
{ text: "Inertia Rating", value: "inrt" },
{ text: "Bonus Weapons Power", value: "wpower" },
{ text: "Bonus Shield Power", value: "spower" },
{ text: "Bonus Engine Power", value: "epower" },
{ text: "Bonus Auxilliary Power", value: "apower" },
{ text: "Fore + Aft Weapons", value: "fa" },
{ text: "Fore Weapons", value: "fore" },
{ text: "Aft Weapons", value: "aft" },
{ text: "Can Equip Dual Cannons", value: "dhc" },
{ text: "Experimental Weapon Slot", value: "exp" },
{ text: "Hangar Bays", value: "hangars" },
{ text: "Devices", value: "dev" },
{ text: "Fleet Grade", value: "fleet" },
{ text: "Tactical Consoles", value: "taccons" },
{ text: "Engineering Consoles", value: "engcons" },
{ text: "Science Consoles", value: "scicons" },
{ text: "Universal Consoles", value: "unicons" },
{ text: "CC: Weapon System Efficiency", value: "weapon" },
{ text: "CC: Shield Frequency Modulation", value: "shield" },
{ text: "CC: Strategic Maneuvering", value: "engine" },
{ text: "CC: Attract Fire", value: "threat" },
{ text: "Secondary Deflector", value: "secdef" },
{ text: "Subsytem Targeting", value: "subtargeting" },
{ text: "Sensor Analysis", value: "sensoranalysis" },
{ text: "Singularity", value: "singularity" },
{ text: "Cloak", value: "cloak" },
{ text: "Flanking", value: "flanking" }
];
